# Generated by Django 6.0.5 on 2026-06-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
