# Generated by Django 6.0.5 on 2026-06-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_avatar_usuario_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='plan',
            field=models.CharField(choices=[('free', 'Unefista'), ('medium', 'Cinéfilo'), ('premium', 'Zerpanito')], default='free', max_length=10),
        ),
    ]
