# Generated by Django 6.0.5 on 2026-05-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('type', models.CharField(choices=[('movie', 'Película'), ('series', 'Serie')], default='movie', max_length=10)),
                ('video_url', models.URLField()),
                ('genres', models.ManyToManyField(to='movies.genre')),
            ],
        ),
    ]
