# Generated by Django 6.0.5 on 2026-05-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
