# Generated by Django 6.0.5 on 2026-05-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop',
            field=models.ImageField(blank=True, null=True, upload_to='backdrops/'),
        ),
    ]
