# Generated by Django 6.0.5 on 2026-05-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_video_file_alter_movie_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duración en minutos', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rotten_tomatoes_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
