# Generated by Django 6.0.5 on 2026-05-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_cast_movie_director_movie_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='URL embed de YouTube', null=True),
        ),
    ]
