# Generated by Django 6.0.5 on 2026-05-22 04:42

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_trailer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Pega cualquier enlace de YouTube aquí', null=True),
        ),
    ]
