# Generated by Django 6.0.5 on 2026-05-22 04:57

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_trailer_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Pega cualquier enlace de Vimeo aquí', null=True),
        ),
    ]
