# Generated by Django 6.0.5 on 2026-06-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_movie_trailer_url_season_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tier',
            field=models.CharField(choices=[('free', 'Gratuito'), ('medium', 'Cinephile'), ('premium', 'Ultra - Estreno')], default='free', max_length=10),
        ),
    ]
