# Generated by Django 6.0.5 on 2026-07-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, help_text="Fecha de estreno. Si es futura, aparece en 'Próximos estrenos'", null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Cantidad de visitas a la ficha'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tier',
            field=models.CharField(choices=[('free', 'Gratuito'), ('medium', 'Cinéfilo'), ('premium', 'Zerpanito')], default='free', max_length=10),
        ),
    ]
