# Generated by Django 6.0.5 on 2026-07-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_movie_release_date_movie_views_alter_movie_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, help_text="ID de IMDb (ej: tt0133093). Requerido si 'is_stream' está activado.", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_stream',
            field=models.BooleanField(default=False, help_text='Activa esto si la película/serie se reproducirá vía Torrentio'),
        ),
    ]
