# Generated by Django 6.0.5 on 2026-07-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_movie_release_date_movie_views_alter_movie_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, help_text='Enlace externo para reproducción completa (Archive.org, Vimeo, etc.). Solo usar con contenido de dominio público o licencia libre. Para Archive.org, usar el formato /embed/, no /details/. Ejemplo correcto: https://archive.org/embed/nosferatu_1922 Ejemplo incorrecto: https://archive.org/details/nosferatu_1922', null=True),
        ),
    ]
