# Generated by Django 6.0.5 on 2026-07-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_movie_imdb_id_movie_is_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='manual_magnet',
            field=models.URLField(blank=True, help_text='Si se rellena, el player usará este link en lugar de buscar automáticamente.', max_length=500, null=True),
        ),
    ]
