# Generated by Django 6.0.5 on 2026-07-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_movie_video_url'),
        ('movies', '0016_movie_manual_magnet'),
    ]

    operations = [
    ]
