# Generated by Django 6.0.5 on 2026-07-06 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_merge_0015_movie_video_url_0016_movie_manual_magnet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imdb_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='is_stream',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='manual_magnet',
        ),
    ]
